export enum SYSTEMS {
  BIOS = 'bios',
  BOOT = 'boot',
  LOGIN = 'login',
  HACK = 'hack',
  HOME = 'home',
  ENTRIES = 'entries',
  LOG = 'log',
  REPAIR = 'repair',
  MAINTENANCE = 'maintenance',
  LIGHTS = 'lights',
  PROGRAMS = 'programs',
  MAP = 'map',
  PING = 'ping',
}
