export enum SYSTEMS {
  BIOS = 'bios',
  BOOT = 'boot',
  LOGIN = 'login',
  HACK = 'hack',
  HOME = 'home',
  ENTRIES = 'entries',
  LOG = 'log',
  REPAIR = 'repair',
  MAINTENANCE = 'maintenance',
  LIGHTS = 'lights',
  PROGRAMS = 'programs',
  NETWORK_MAP = 'network_map',
  NETWORK_SEARCH = 'network_search',
  POWER_DISTRIBUTOR = 'power_distributor',
}
